### ISSUE TITLE
ecepostgres image not found

### ISSUE THREAD

**Issue by EduJGURJC** [elastest/elastest-cost-engine#1]
Hi,
I'm trying to use ECE with docker-compose but can not find ecepostgres image. Has the image been uploaded to a DockerHub repository?

`ERROR: repository ecepostgres not found: does not exist or no pull access`

Thank you in advance for your help

**Comment by ManuPerezBelmonte** [comment]
Hi Edu, 

At the moment, ECE is using postgres as a prototype data layer while ECE is not connected to the rest of the components. For that reason the image of postgres hasn't been published into the dockerhub repository.

As said in the [documentation](https://github.com/elastest/elastest-cost-engine/blob/master/docs/index.md#how-to-run):

1. Install Docker.

2. Install Docker Compose. 

3. Go to the `postgres` folder and build the database image:
   - `docker build -t postgres .`
4. Go back to the root folder of the repository and build the main ECE image:
   - `docker build -t ece .`
5. Run the image using the following command:
   - `docker-compose up`

Cheers

**Comment by EduJGURJC** [comment]
Ok,
Thank you Manu
