### ISSUE TITLE
Errors on run ECE with docker-compose.yml

### ISSUE THREAD

**Issue by EduJGURJC** [elastest/elastest-cost-engine#2]
Hi,

there are errors on run ECE with docker-compose.yml file:

![seleccion_005](https://user-images.githubusercontent.com/26252085/31131883-aae97a72-a85b-11e7-8ed3-2b6f71522cba.png)

![seleccion_006](https://user-images.githubusercontent.com/26252085/31132087-28861fb2-a85c-11e7-91d0-a5419113a8e5.png)

**Comment by ManuPerezBelmonte** [comment]
Hi edu, 

Can you pull the repo? I fixed it yesterday at 16:40 and worked in the CI.

Please let me know if the issue doesn't get solved

Manu

**Comment by EduJGURJC** [comment]
Hi,

no, I did the pull yesterday at 17 or so, and I've tried it again now, but I have the same problem.

**Comment by ManuPerezBelmonte** [comment]
Fixed in 1f5ee98

**Comment by EduJGURJC** [comment]
Working!
